// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/group_chat.proto

package com.jiangfucheng.im.protobuf;

public final class GroupChat {
  private GroupChat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GroupChatRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jiangfucheng.im.protobuf.GroupChatRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 msg_id = 1;</code>
     * @return The msgId.
     */
    long getMsgId();

    /**
     * <code>int64 group_id = 2;</code>
     * @return The groupId.
     */
    long getGroupId();

    /**
     * <code>int64 from_id = 3;</code>
     * @return The fromId.
     */
    long getFromId();

    /**
     * <code>int32 type = 4;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>string content = 5;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 5;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>string token = 6;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 6;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code com.jiangfucheng.im.protobuf.GroupChatRequest}
   */
  public  static final class GroupChatRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jiangfucheng.im.protobuf.GroupChatRequest)
      GroupChatRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GroupChatRequest.newBuilder() to construct.
    private GroupChatRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GroupChatRequest() {
      content_ = "";
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GroupChatRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GroupChatRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgId_ = input.readInt64();
              break;
            }
            case 16: {

              groupId_ = input.readInt64();
              break;
            }
            case 24: {

              fromId_ = input.readInt64();
              break;
            }
            case 32: {

              type_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jiangfucheng.im.protobuf.GroupChat.internal_static_com_jiangfucheng_im_protobuf_GroupChatRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jiangfucheng.im.protobuf.GroupChat.internal_static_com_jiangfucheng_im_protobuf_GroupChatRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest.class, com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest.Builder.class);
    }

    public static final int MSG_ID_FIELD_NUMBER = 1;
    private long msgId_;
    /**
     * <code>int64 msg_id = 1;</code>
     * @return The msgId.
     */
    public long getMsgId() {
      return msgId_;
    }

    public static final int GROUP_ID_FIELD_NUMBER = 2;
    private long groupId_;
    /**
     * <code>int64 group_id = 2;</code>
     * @return The groupId.
     */
    public long getGroupId() {
      return groupId_;
    }

    public static final int FROM_ID_FIELD_NUMBER = 3;
    private long fromId_;
    /**
     * <code>int64 from_id = 3;</code>
     * @return The fromId.
     */
    public long getFromId() {
      return fromId_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>int32 type = 4;</code>
     * @return The type.
     */
    public int getType() {
      return type_;
    }

    public static final int CONTENT_FIELD_NUMBER = 5;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 5;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 5;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 6;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 6;</code>
     * @return The token.
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 6;</code>
     * @return The bytes for token.
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgId_ != 0L) {
        output.writeInt64(1, msgId_);
      }
      if (groupId_ != 0L) {
        output.writeInt64(2, groupId_);
      }
      if (fromId_ != 0L) {
        output.writeInt64(3, fromId_);
      }
      if (type_ != 0) {
        output.writeInt32(4, type_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, content_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, token_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, msgId_);
      }
      if (groupId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, groupId_);
      }
      if (fromId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, fromId_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, type_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, content_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, token_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest)) {
        return super.equals(obj);
      }
      com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest other = (com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest) obj;

      if (getMsgId()
          != other.getMsgId()) return false;
      if (getGroupId()
          != other.getGroupId()) return false;
      if (getFromId()
          != other.getFromId()) return false;
      if (getType()
          != other.getType()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (37 * hash) + GROUP_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGroupId());
      hash = (37 * hash) + FROM_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFromId());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jiangfucheng.im.protobuf.GroupChatRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jiangfucheng.im.protobuf.GroupChatRequest)
        com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jiangfucheng.im.protobuf.GroupChat.internal_static_com_jiangfucheng_im_protobuf_GroupChatRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jiangfucheng.im.protobuf.GroupChat.internal_static_com_jiangfucheng_im_protobuf_GroupChatRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest.class, com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest.Builder.class);
      }

      // Construct using com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgId_ = 0L;

        groupId_ = 0L;

        fromId_ = 0L;

        type_ = 0;

        content_ = "";

        token_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jiangfucheng.im.protobuf.GroupChat.internal_static_com_jiangfucheng_im_protobuf_GroupChatRequest_descriptor;
      }

      @java.lang.Override
      public com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest getDefaultInstanceForType() {
        return com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest build() {
        com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest buildPartial() {
        com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest result = new com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest(this);
        result.msgId_ = msgId_;
        result.groupId_ = groupId_;
        result.fromId_ = fromId_;
        result.type_ = type_;
        result.content_ = content_;
        result.token_ = token_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest) {
          return mergeFrom((com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest other) {
        if (other == com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest.getDefaultInstance()) return this;
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        if (other.getGroupId() != 0L) {
          setGroupId(other.getGroupId());
        }
        if (other.getFromId() != 0L) {
          setFromId(other.getFromId());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long msgId_ ;
      /**
       * <code>int64 msg_id = 1;</code>
       * @return The msgId.
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <code>int64 msg_id = 1;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 msg_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }

      private long groupId_ ;
      /**
       * <code>int64 group_id = 2;</code>
       * @return The groupId.
       */
      public long getGroupId() {
        return groupId_;
      }
      /**
       * <code>int64 group_id = 2;</code>
       * @param value The groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupId(long value) {
        
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 group_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupId() {
        
        groupId_ = 0L;
        onChanged();
        return this;
      }

      private long fromId_ ;
      /**
       * <code>int64 from_id = 3;</code>
       * @return The fromId.
       */
      public long getFromId() {
        return fromId_;
      }
      /**
       * <code>int64 from_id = 3;</code>
       * @param value The fromId to set.
       * @return This builder for chaining.
       */
      public Builder setFromId(long value) {
        
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 from_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromId() {
        
        fromId_ = 0L;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 4;</code>
       * @return The type.
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 4;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 5;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 5;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 5;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 5;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 6;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 6;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 6;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 6;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jiangfucheng.im.protobuf.GroupChatRequest)
    }

    // @@protoc_insertion_point(class_scope:com.jiangfucheng.im.protobuf.GroupChatRequest)
    private static final com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest();
    }

    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GroupChatRequest>
        PARSER = new com.google.protobuf.AbstractParser<GroupChatRequest>() {
      @java.lang.Override
      public GroupChatRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GroupChatRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GroupChatRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GroupChatRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.jiangfucheng.im.protobuf.GroupChat.GroupChatRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GroupChatResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jiangfucheng.im.protobuf.GroupChatResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 msg_id = 1;</code>
     * @return The msgId.
     */
    long getMsgId();

    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>int64 from_id = 3;</code>
     * @return The fromId.
     */
    long getFromId();

    /**
     * <code>int64 group_id = 4;</code>
     * @return The groupId.
     */
    long getGroupId();
  }
  /**
   * Protobuf type {@code com.jiangfucheng.im.protobuf.GroupChatResponse}
   */
  public  static final class GroupChatResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jiangfucheng.im.protobuf.GroupChatResponse)
      GroupChatResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GroupChatResponse.newBuilder() to construct.
    private GroupChatResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GroupChatResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GroupChatResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GroupChatResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgId_ = input.readInt64();
              break;
            }
            case 16: {

              timestamp_ = input.readInt64();
              break;
            }
            case 24: {

              fromId_ = input.readInt64();
              break;
            }
            case 32: {

              groupId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jiangfucheng.im.protobuf.GroupChat.internal_static_com_jiangfucheng_im_protobuf_GroupChatResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jiangfucheng.im.protobuf.GroupChat.internal_static_com_jiangfucheng_im_protobuf_GroupChatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse.class, com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse.Builder.class);
    }

    public static final int MSG_ID_FIELD_NUMBER = 1;
    private long msgId_;
    /**
     * <code>int64 msg_id = 1;</code>
     * @return The msgId.
     */
    public long getMsgId() {
      return msgId_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int FROM_ID_FIELD_NUMBER = 3;
    private long fromId_;
    /**
     * <code>int64 from_id = 3;</code>
     * @return The fromId.
     */
    public long getFromId() {
      return fromId_;
    }

    public static final int GROUP_ID_FIELD_NUMBER = 4;
    private long groupId_;
    /**
     * <code>int64 group_id = 4;</code>
     * @return The groupId.
     */
    public long getGroupId() {
      return groupId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgId_ != 0L) {
        output.writeInt64(1, msgId_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(2, timestamp_);
      }
      if (fromId_ != 0L) {
        output.writeInt64(3, fromId_);
      }
      if (groupId_ != 0L) {
        output.writeInt64(4, groupId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, msgId_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (fromId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, fromId_);
      }
      if (groupId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, groupId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse)) {
        return super.equals(obj);
      }
      com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse other = (com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse) obj;

      if (getMsgId()
          != other.getMsgId()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (getFromId()
          != other.getFromId()) return false;
      if (getGroupId()
          != other.getGroupId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + FROM_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFromId());
      hash = (37 * hash) + GROUP_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGroupId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jiangfucheng.im.protobuf.GroupChatResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jiangfucheng.im.protobuf.GroupChatResponse)
        com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jiangfucheng.im.protobuf.GroupChat.internal_static_com_jiangfucheng_im_protobuf_GroupChatResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jiangfucheng.im.protobuf.GroupChat.internal_static_com_jiangfucheng_im_protobuf_GroupChatResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse.class, com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse.Builder.class);
      }

      // Construct using com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgId_ = 0L;

        timestamp_ = 0L;

        fromId_ = 0L;

        groupId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jiangfucheng.im.protobuf.GroupChat.internal_static_com_jiangfucheng_im_protobuf_GroupChatResponse_descriptor;
      }

      @java.lang.Override
      public com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse getDefaultInstanceForType() {
        return com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse build() {
        com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse buildPartial() {
        com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse result = new com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse(this);
        result.msgId_ = msgId_;
        result.timestamp_ = timestamp_;
        result.fromId_ = fromId_;
        result.groupId_ = groupId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse) {
          return mergeFrom((com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse other) {
        if (other == com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse.getDefaultInstance()) return this;
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getFromId() != 0L) {
          setFromId(other.getFromId());
        }
        if (other.getGroupId() != 0L) {
          setGroupId(other.getGroupId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long msgId_ ;
      /**
       * <code>int64 msg_id = 1;</code>
       * @return The msgId.
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <code>int64 msg_id = 1;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 msg_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 2;</code>
       * @return The timestamp.
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private long fromId_ ;
      /**
       * <code>int64 from_id = 3;</code>
       * @return The fromId.
       */
      public long getFromId() {
        return fromId_;
      }
      /**
       * <code>int64 from_id = 3;</code>
       * @param value The fromId to set.
       * @return This builder for chaining.
       */
      public Builder setFromId(long value) {
        
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 from_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromId() {
        
        fromId_ = 0L;
        onChanged();
        return this;
      }

      private long groupId_ ;
      /**
       * <code>int64 group_id = 4;</code>
       * @return The groupId.
       */
      public long getGroupId() {
        return groupId_;
      }
      /**
       * <code>int64 group_id = 4;</code>
       * @param value The groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupId(long value) {
        
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 group_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupId() {
        
        groupId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jiangfucheng.im.protobuf.GroupChatResponse)
    }

    // @@protoc_insertion_point(class_scope:com.jiangfucheng.im.protobuf.GroupChatResponse)
    private static final com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse();
    }

    public static com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GroupChatResponse>
        PARSER = new com.google.protobuf.AbstractParser<GroupChatResponse>() {
      @java.lang.Override
      public GroupChatResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GroupChatResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GroupChatResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GroupChatResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.jiangfucheng.im.protobuf.GroupChat.GroupChatResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jiangfucheng_im_protobuf_GroupChatRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jiangfucheng_im_protobuf_GroupChatRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jiangfucheng_im_protobuf_GroupChatResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jiangfucheng_im_protobuf_GroupChatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031protobuf/group_chat.proto\022\034com.jiangfu" +
      "cheng.im.protobuf\"s\n\020GroupChatRequest\022\016\n" +
      "\006msg_id\030\001 \001(\003\022\020\n\010group_id\030\002 \001(\003\022\017\n\007from_" +
      "id\030\003 \001(\003\022\014\n\004type\030\004 \001(\005\022\017\n\007content\030\005 \001(\t\022" +
      "\r\n\005token\030\006 \001(\t\"Y\n\021GroupChatResponse\022\016\n\006m" +
      "sg_id\030\001 \001(\003\022\021\n\ttimestamp\030\002 \001(\003\022\017\n\007from_i" +
      "d\030\003 \001(\003\022\020\n\010group_id\030\004 \001(\003B)\n\034com.jiangfu" +
      "cheng.im.protobufB\tGroupChatb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_jiangfucheng_im_protobuf_GroupChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jiangfucheng_im_protobuf_GroupChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jiangfucheng_im_protobuf_GroupChatRequest_descriptor,
        new java.lang.String[] { "MsgId", "GroupId", "FromId", "Type", "Content", "Token", });
    internal_static_com_jiangfucheng_im_protobuf_GroupChatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_jiangfucheng_im_protobuf_GroupChatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jiangfucheng_im_protobuf_GroupChatResponse_descriptor,
        new java.lang.String[] { "MsgId", "Timestamp", "FromId", "GroupId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
