chat:
  message:
    retry: 5
    retry-delay-time: 1000
    failed: 3
    failed-delay-time: 1000
  heart-beat:
    period: 15000

http-server:
  ip: localhost
  port: 80

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://192.168.5.134:3306/im?useSSL=false&serverTimezone=UTC&charset=utf-8
    #    utils: jdbc:mysql://localhost:3306/im?useSSL=false&serverTimezone=UTC&charset=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
server:
  port: 8012

id:
  worker: 3
  data-center: 3