server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://192.168.5.134:3306/im?useSSL=false&serverTimezone=UTC&charset=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
    allow-bean-definition-overriding: true

#id生成器配置
id:
  worker: 1
  data-center: 1
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ok:
  http:
    connect-timeout: 30
    read-timeout: 30
    write-timeout: 30
    max-idle-connections: 200
    keep-alive-duration: 300

redis:
  host: 192.168.5.134
  port: 6380
  password: 123456

zookeeper:
  address: 192.168.5.134:2181
  timeout: 50000

im:
  download:
    path: G:/im/download
